# Tip schema

# --- !Ups
CREATE TABLE "tips" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "tip" varchar not null
);

# --- !Downs
drop TABLE "tips" if exists;